export default [
  'Progressive disclosure',
  'Red route',
  'Stakeholder Interviews',
  'Usability engineering',
  'User-centred design',
  'User journey',
  'Lean UX',
  'Iterative design',
  'Information scent',
  'The Double Diamond',
  'Principles Over Standards',
  'Accessibility First',
  'Functional Programming',
  'Offline Web Apps',
  'Shadow DOM',
  'Continuous integration',
  'Test-driven development',
  'Pair programming',
  'Experience design',
  'Module bundlers',
  'React',
  'Redux',
  'Application architectures',
  'ES2017',
  'Jest',
  'Visual regression testing',
  'Snapshot testing',
  'Type inference',
  'RxJS',
  'Focus on affordance',
  'Forward thinking',
  'Leadership',
  'Mentoring',
  'Internet of things',
  'Async functions'
]
